<?

$response = false;
$response = @$this->response;

header('Cache-Control: no-cache, must-revalidate');
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
header('Content-type: text/javascript');

if (isset($response['data']) && !empty($response['status'])) {
    $records = array();
    foreach ($response['data'] as $record) {
        $records[] = is_array($record) ? array_values($record) : $record;
    }
    $response['data'] = $records;
}


$json = json_encode($response, JSON_NUMERIC_CHECK);
$callback = Zend_Registry::isRegistered('callback') ? Zend_Registry::get('callback') : false;

if (!empty($callback)) {
    echo "$callback($json)";
} else {
    echo $json;
}
exit;
