<?php

    if ( isset($this->window)) {
    	
         if ( isset($this->layout()->content) || isset($this->layout()->data)) {
           $this->window['content'] = empty($this->layout()->content) ? $this->layout()->data : $this->layout()->content;
         }

         if ( isset($this->script)) {
           $this->window['script'] = $this->script;
         }
         
         
    	 echo json_encode( $this->window );
  	 
    }